name: Go

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v
      
    - name: ls
      run: ls
      
    - name: make release
      if: github.event.ref_type == 'tag'
      uses: actions-cool/release-helper@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        triger: 'tag'
        changelogs: 'CHANGELOG.en-US.md, CHANGELOG.zh-CN.md'
        branch: 'master'
    
